global:
  scrape_interval: 15s # Recolecta métricas cada 15 segundos.

# Carga los archivos de reglas de alerta
rule_files:
  - "alert.rules.yml"

# Configuración de Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  # Trabajo para monitorear a Prometheus mismo.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Trabajo para monitorear las métricas del servidor anfitrión.
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Trabajo para monitorear las métricas de los contenedores Docker.
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']